<?php

$aios_initial_setup_aios_cf7_before_send = new aios_cf7_before_send();

class aios_cf7_before_send {

	function __construct() {

		add_action( 'wpcf7_before_send_mail',  array( $this, 'aios_cf7_before_email_send' ) );

	}

	function aios_cf7_before_email_send( $wpcf7 ) {
		global $aios_cf7_var;
        extract( $aios_cf7_var );
		
		$submission = WPCF7_Submission::get_instance();
		$wpcf7      = WPCF7_ContactForm::get_current();
		
		if ( $submission ) {

			$data  = $submission->get_posted_data();
			$mail  = $wpcf7->prop('mail');
			$mail2 = $wpcf7->prop('mail_2');

			if( $wpcf7->title == 'Free Home Valuation (Auto-generated by AIOS Home Valuation)' ) return;

			$c_header = '<table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="padding-top: 25px; padding-bottom: 25px;">
				<tr>
					<td align="center" valign="top">
						<table width="600" border="0" cellspacing="0" cellpadding="0">
							<tr>
								<td align="center" valign="top" bgcolor="#ffffff" style="padding-bottom: 20px; border-bottom: solid 1px #cacaca;' . $client_font_style . '">
									' . $header_client . '
								</td>
							</tr>
							<tr>
								<td align="left" valign="top" bgcolor="#ffffff" style="padding: 20px 0 10px;' . $client_font_style . '">
									' . $intro_client . '
								</td>
							</tr>
							<tr>
								<td align="left" valign="top" bgcolor="#ffffff" style="padding: 0;' . $client_font_style . '">';
			$c_footer = 		'</td>
							</tr>
							<tr>
								<td align="left" valign="top" bgcolor="#ffffff" style="padding: 10px 0 20px;' . $client_font_style . '">
									' . $closing_client . '
								</td>
							</tr>
							<tr>
								<td align="center" valign="top" bgcolor="#ffffff" style="padding-top: 20px; border-top: solid 1px #cacaca;' . $client_font_style . '">
									' . $footer_client . '
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>';

			$reply_to 			= str_replace( 'Reply-To: ', '', $mail[ 'additional_headers' ] );
			$body 				= $c_header . $mail[ 'body' ] . $c_footer;
			$body 				= str_replace( '{reply-to}', $reply_to, $body );
			$clean_body 		= $mail[ 'body' ];
			$mail['body']  		= do_shortcode( $body );
			$mail['use_html']  	= 1;


			$u_header = '<table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="padding-top: 25px; padding-bottom: 25px;">
				<tr>
					<td align="center" valign="top">
						<table width="600" border="0" cellspacing="0" cellpadding="0">
							<tr>
								<td align="center" valign="top" bgcolor="#ffffff" style="padding-bottom: 20px; border-bottom: solid 1px #cacaca;' . $user_font_style . '">
									' . $header_user . '
								</td>
							</tr>
							<tr>
								<td align="left" valign="top" bgcolor="#ffffff" style="padding: 20px 0 10px;' . $user_font_style . '">
									' . $intro_user . '
								</td>
							</tr>
							<tr>
								<td align="left" valign="top" bgcolor="#ffffff" style="padding: 0;' . $user_font_style . '">';
			$u_footer = 		'</td>
							</tr>
							<tr>
								<td align="left" valign="top" bgcolor="#ffffff" style="padding: 10px 0 20px;' . $user_font_style . '">
									' . $closing_user . '
								</td>
							</tr>
							<tr>
								<td align="center" valign="top" bgcolor="#ffffff" style="padding-top: 20px; border-top: solid 1px #cacaca;' . $user_font_style . '">
									' . $footer_user . '
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>';

			/** Auto responder value **/
			$responder_to					= $mail2[ 'active' ] == 1 ? $mail2['recipient'] : $reply_to;
			$responder_from					= $mail2[ 'active' ] == 1 ? $mail2['from'] : $mail[ 'recipient' ];
			$responder_subject 				= $mail2[ 'active' ] == 1 ? $mail2['subject'] : $subject_user;
			$responder_body					= $mail2[ 'active' ] == 1 ? $mail2[ 'body' ] : $clean_body;

            /** Activate Mail2 to enable send auto responder **/
            if( $opt_user_confirmation != '1' ) {
                $mail2['active']				= 1;
    
                $mail2['recipient']				= do_shortcode( $responder_to );
                $mail2['from'] 					= $responder_from;
                $mail2['subject'] 				= $responder_subject;
                $body2 							= $u_header . $responder_body . $u_footer;
                $mail2['body'] 					= do_shortcode( $body2 );
                $mail2['additional_headers'] 	= 1;
                $mail2['use_html'] 				= 'Reply-To: ' . $mail[ 'recipient' ];
                $wpcf7->set_properties( array( "mail" => $mail, "mail_2" => $mail2 ) );
            } else {
			    $wpcf7->set_properties( array( "mail" => $mail ) );
            }

			return $wpcf7;
		}

	}

}

?>