<?php 
	$placeholder_val = array(
		"photo_left" 		=> AIOS_INITIAL_SETUP_URL . 'includes/assets/images/404-text-image.png' ,
		"photo_right" 		=> AIOS_INITIAL_SETUP_URL . 'includes/assets/images/404-image-right.png',
		"error_verbiage" 	=> "Please check the webpage URL to make sure you have the correct address. It may also be possible that the content of this page is not yet ready for viewing. Feel free to revisit this page at another time or contact the website administrator for further assistance.",
		"error_form" 		=> "[contact-form-7 title='404 Page Form (Auto-generated by AIOS Initial Setup)' html_class='use-floating-validation-tip']",
		"error_template" 	=> "sidebar"
	);

	$form_val  			= ( get_option('404_settings') != null ? get_option('404_settings') : $placeholder_val );
	$photo_left	 		= ( !empty( $form_val['photo_left'] ) ? $form_val['photo_left'] : $placeholder_val['photo_left'] );
	$photo_right	 	= ( !empty( $form_val['photo_right'] ) ? $form_val['photo_right'] : $placeholder_val['photo_right'] );
	$error_verbiage	 	= ( !empty( $form_val['error_verbiage'] ) ? $form_val['error_verbiage'] : $placeholder_val['error_verbiage'] );
	$error_form	 		= ( !empty( $form_val['error_form'] ) ? $form_val['error_form'] : $placeholder_val['error_form'] );
	$error_template	 	= ( !empty( $form_val['error_template'] ) ? $form_val['error_template'] : $placeholder_val['error_template'] );
	$invert_color	 	= ( !empty( $form_val['invert_color'] ) ? 'checked="checked"' : '' );
	$disabled_404	 	= ( !empty( $form_val['disabled_404'] ) ? 'checked="checked"' : '' );
?>

<!-- BEGIN: Row Box -->
<div class="wpui-row wpui-row-box">
	<div class="wpui-col-md-3">
		<p>
			<span class="wpui-settings-title">Left Image</span>
			<strong>Recommend Size: Max Width</strong> 380px x Max Height 82px
		</p>
	</div>
	<div class="wpui-col-md-9">
		<div class="setting-content setting-container setting-container-logo setting-container-parent">
			<p></p>
			<div class="setting-logo-preview setting-image-preview">
				<img src="<?=$photo_left;?>">
			</div>
			<input type="text" class="setting-image-input" name="404_settings[photo_left]" id="404_settings[photo_left]" value="<?=$photo_left?>" style="display: none;">
			<div class="setting-button mt-3">
				<input type="button" class="setting-upload wpui-secondary-button" value="Upload">
				<input type="button" class="setting-remove wpui-default-button" value="Remove">
			</div>
		</div>
	</div>
</div>
<!-- END: Row Box -->

<!-- BEGIN: Row Box -->
<div class="wpui-row wpui-row-box">
	<div class="wpui-col-md-3">
		<p>
			<span class="wpui-settings-title">Right Image</span>
			<strong>Recommend Size: Max Width</strong> 380px x Max Height 82px
		</p>
	</div>
	<div class="wpui-col-md-9">
		<div class="setting-content setting-container setting-container-logo setting-container-parent">
			<div class="setting-logo-preview setting-image-preview">
				<img src="<?=$photo_right;?>">
			</div>
			<input type="text" class="setting-image-input" name="404_settings[photo_right]" id="404_settings[photo_right]" value="<?=$photo_right?>" style="display: none;">
			<div class="setting-button mt-3">
				<input type="button" class="setting-upload wpui-secondary-button" value="Upload">
				<input type="button" class="setting-remove wpui-default-button" value="Remove">
			</div>
		</div>
	</div>
</div>
<!-- END: Row Box -->

<!-- BEGIN: Row Box -->
<div class="wpui-row wpui-row-box">
	<div class="wpui-col-md-3">
		<p><span class="wpui-settings-title">Verbiage</span></p>
	</div>
	<div class="wpui-col-md-9">
		<div class="form-group">
			<textarea id="404_settings[error_verbiage]" name="404_settings[error_verbiage]"><?=$error_verbiage?></textarea>
		</div>
	</div>
</div>
<!-- END: Row Box -->

<!-- BEGIN: Row Box -->
<div class="wpui-row wpui-row-box">
	<div class="wpui-col-md-3">
		<p><span class="wpui-settings-title">Shortcode</span></p>
	</div>
	<div class="wpui-col-md-9">
		<div class="form-group">
			<textarea id="404_settings[error_form]" name="404_settings[error_form]"><?=stripslashes($error_form)?></textarea>
		</div>
	</div>
</div>
<!-- END: Row Box -->

<!-- BEGIN: Row Box -->
<div class="wpui-row wpui-row-box">
	<div class="wpui-col-md-3">
		<p><span class="wpui-settings-title">Template</span></p>
	</div>
	<div class="wpui-col-md-9">
		<div class="form-group">
			<select name="404_settings[error_template]" id="404_settings[error_template]">
				<option value="content-full" <?=($error_template == "content-full" ? "selected" : '')?>>Full Width</option>
				<option value="content-sidebar" <?=($error_template == "content-sidebar" ? "selected" : '')?>>with Sidebar</option>
			</select>
		</div>
	</div>
</div>
<!-- END: Row Box -->

<!-- BEGIN: Row Box -->
<div class="wpui-row wpui-row-box">
	<div class="wpui-col-md-3">
		<p><span class="wpui-settings-title">Invert Color</span></p>
	</div>
	<div class="wpui-col-md-9">
		<div class="form-group">
			<div class="form-checkbox-group form-toggle-switch" data-choices="true">
				<div class="form-checkbox">
					<label>
						<input type="checkbox" id="invert_color" name="404_settings[invert_color]" value="1" <?=$invert_color?>> Dark Interface
					</label>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- END: Row Box -->

<!-- BEGIN: Row Box -->
<div class="wpui-row wpui-row-box">
	<div class="wpui-col-md-3">
		<p><span class="wpui-settings-title">404 Page</span></p>
	</div>
	<div class="wpui-col-md-9">
		<div class="form-group">
			<div class="form-checkbox-group form-toggle-switch" data-choices="true">
				<div class="form-checkbox">
					<label>
						<input type="checkbox" id="disabled_404" name="404_settings[disabled_404]" value="1" <?=$disabled_404?>> Disable Initial Setup 404 Page
						<span class="form-group-description">Enable this option allow user to add 404.php of the active theme</span>
					</label>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- END: Row Box -->

<!-- BEGIN: Save Changes -->
<div class="wpui-row wpui-row-submit">
	<div class="wpui-col-md-12">
		<div class="form-group">
			<input type="submit" class="save-option-ajax wpui-secondary-button text-uppercase" value="Save Changes">
		</div>
	</div>
</div>
<!-- END: Save Changes -->