<?php
	if (  isset( $_POST['generate_cf7_nonce'] ) &&  wp_verify_nonce( $_POST['generate_cf7_nonce'], 'generate_cf7_action' ) ) { 
		$query = new WP_Query( array( 'post_type' => 'wpcf7_contact_form' ) );
		while ( $query->have_posts() ) {
			$query->the_post();
			$additional_settings = array_filter( get_post_meta( get_the_ID(), '_additional_settings' ) );

			if ( !empty( $additional_settings ) ) {
				update_post_meta( get_the_ID(), '_additional_settings', '' );
				echo 'Done removing data on ' . get_the_title() . '<br>';
			}

		}
	} else {

		echo '<h3>Contact Forms 7:</h3>';
		$query = new WP_Query( array( 'post_type' => 'wpcf7_contact_form' ) );
		while ( $query->have_posts() ) {
			$query->the_post();
			$additional_settings = array_filter( get_post_meta( get_the_ID(), '_additional_settings' ) );
			echo '- ' . get_the_title() . '<br>';
		}
	?>
		<p><em><strong>Note:</strong> No need to change title if contact title has "<strong>(Auto-generated by AIOS Initial Setup)</strong>" this will automatically remove.</em></p>
		<hr>
		<form method="post">
			<?php wp_nonce_field('generate_cf7_action','generate_cf7_nonce'); ?>
			<input type="submit" name="btnSubmit" class="button button-primary button-large"  value="Remove all additional setting on all contact form 7 forms. ">
			<p><em><strong>Note:</strong> Before doing this make sure you back-up the database using Updrafts, there's no way of reverting it without a backup.</em></p>
		</form>
	<?php
	}
?>