<?php
/**
 * This will initialize the plugin
 *
 * @since 2.8.6
 */
if ( !class_exists( 'aios_initial_setup_init_404_page' ) ) {
	
	class aios_initial_setup_init_404_page{

		/**
		 * Constructor
		 *
		 * @since 1.0.0
		 *
		 * @access public
		 */
		public function __construct() {
			$this->save_error_options( $_POST );
			$this->add_actions();
		}

		/**
		 * Save Front End Settings
		 *
		 * @since 2.8.5
		 *
		 * @access public
		 */	
		public function save_error_options( $post_date ) {
			$placeholder_val = array(
				"photo_left" => AIOS_INITIAL_SETUP_URL .'/includes/assets/images/404-text-image.png' ,
				"photo_right" => AIOS_INITIAL_SETUP_URL .'/includes/assets/images/404-image-right.png',
				"error_verbiage" => "Please check the webpage URL to make sure you have the correct address. It may also be possible that the content of this page is not yet ready for viewing. Feel free to revisit this page at another time or contact the website administrator for further assistance.",
				"error_form" => "[contact-form-7 title='404 Page Form (Auto-generated by AIOS Initial Setup)' html_class='use-floating-validation-tip']",
				"error_template" => "sidebar"
			);

			if( get_option( '404_settings' ) == "" ){
				update_option( '404_settings', $placeholder_val );
			} else {
				if( isset( $_POST[ 'error-form-flag' ] ) ) {
				  	if (! isset( $post_date[ 'error_fields_content' ]) && wp_verify_nonce( $_POST[ 'error_fields_content' ], 'error_fields_action' ) ) return;
					$error_options = array(
						"photo_left" => ( isset($post_date['error-left-photo'] ) ? sanitize_text_field( $post_date['error-left-photo'] ) : '') ,
						"photo_right" => ( isset($post_date['error-right-photo'] ) ? sanitize_text_field( $post_date['error-right-photo'] ) : '') ,
						"error_verbiage" => ( isset($post_date['error-verbiage'] ) ? sanitize_text_field( $post_date['error-verbiage'] ) : '') ,
						"error_form" => ( isset($post_date['error-form'] ) ? sanitize_text_field( $post_date['error-form'] )  : '') ,
						"error_template" => ( isset($post_date['error-template'] ) ? sanitize_text_field( $post_date['error-template'] )  : '' )
					);
					update_option('404_settings', ( isset( $error_options ) ? $error_options : '') );
				}
			}
		}


		/**
		 * Add Actions.
		 *
		 * @since 1.0.0
		 *
		 * @access protected
		 */
		protected function add_actions() {
			$settings = get_option('404_settings');
			if ( empty( $settings['disabled_404'] ) ) {
				add_filter( 'template_include', array( $this, 'aios_404_page_template'), 11 );
			}
		}

		/**
		 * Call 404 Page
		 *
		 * @since 2.8.5
		 *
		 * @access public
		 */	
		public function aios_404_page_template( $template ) {

			if ( is_404() ) {
				return AIOS_INITIAL_SETUP_DIR . 'includes/functions/404-page-style/404-page.php';
			}

			return $template;
		}

	}
	
	$aios_initial_setup_init_404_page = new aios_initial_setup_init_404_page();

}