<form method="post">
	<!-- BEGIN: Row Box -->
	<div class="wpui-row wpui-row-box">
		<div class="wpui-col-md-3">
			<p>
				<span class="wpui-settings-title">Page Title</span>
				Enter Page Titles separated by new lines.
			</p>
		</div>
		<div class="wpui-col-md-9">
			<textarea id="pages-to-create" data-required="true" style="min-height: 100px;"></textarea>
		</div>
	</div>
	<!-- END: Row Box -->
	<!-- BEGIN: Row Box -->
	<div class="wpui-row wpui-row-box">
		<div class="wpui-col-md-3">
			<p>
				<span class="wpui-settings-title">Page Content</span>
				You need to generate contact page/form first before generating pages.
			</p>
		</div>
		<div class="wpui-col-md-9">
			<textarea id="pages-content" style="min-height: 200px;"><strong>Thank you for visiting <?php echo get_bloginfo( 'title' ) ?>!</strong>
We have scheduled an update for this section of the website, and invite you to come back at a later date to view our new content.
<?php
	$cf7_query = new WP_Query( array( 'post_type' => 'wpcf7_contact_form', 's' => 'Contact Us (Auto-generated by AIOS Initial Setup)' ) );
	$cf7_query = $cf7_query->posts;
	$cf7_query = array_filter( $cf7_query );
	if ( !empty( $cf7_query ) ) {
		echo '
From here, feel free to go back to our <a href="' . get_bloginfo( 'url' ) . '"><strong>Homepage</strong></a>, or send us any inquiries you may have and we\'ll get right back in touch.

<div class="aidefcf-wrapper aidefcf-wrapper-contact-us-(auto-generated-by-aios-initial-setup)">[contact-form-7 id="' . $cf7_query[0]->ID . '" title="Contact Us (Auto-generated by AIOS Initial Setup)" html_class="use-floating-validation-tip"]</div>';
	} else {
		echo '
From here, feel free to go back to our <a href="' . get_bloginfo( 'url' ) . '"><strong>Homepage</strong></a>.';
	}
?></textarea>
		</div>
	</div>
	<!-- END: Row Box -->
	<!-- BEGIN: Row Box -->
	<div class="wpui-row wpui-row-box">
		<div class="wpui-col-md-3">
			<p>
				<span class="wpui-settings-title">Page Status</span>
			</p>
		</div>
		<div class="wpui-col-md-9">
			<select id="page-status">
				<option value="publish">Publish</option>
				<option value="pending">Pending Review</option>
				<option value="draft">Draft</option>
			</select>
		</div>
	</div>
	<!-- END: Row Box -->
	<!-- BEGIN: Row Box -->
	<div class="wpui-row wpui-row-box">
		<div class="wpui-col-md-3">
			<p>
				<span class="wpui-settings-title">Parent</span>
			</p>
		</div>
		<div class="wpui-col-md-9">
			<select id="page-parent">
				<option value="0">(no parent)</option>
				<?php 
					$page_args = array(
						'sort_order' 	=> 'asc',
						'sort_column' 	=> 'post_title',
						'post_type' 	=> 'page',
						'post_status' 	=> 'publish'
					); 

					$pages = get_pages($page_args);

					if( $pages ) {
						foreach ($pages as $key => $value) {
							echo '<option value=' . $value->ID . '>' . $value->post_title . '</option>';
						}
					}
				?>
			</select>
		</div>
	</div>
	<!-- END: Row Box -->
	<!-- BEGIN: Row Box -->
	<div class="wpui-row wpui-row-box">
		<div class="wpui-col-md-3">
			<p>
				<span class="wpui-settings-title">Template</span>
			</p>
		</div>
		<div class="wpui-col-md-9">
			<select id="page-template">
				<option value="">Default</option>
				<?php 
					$templates = get_page_templates();

					if( $templates ) {
						foreach ( $templates as $template_name => $template_filename ) {
							echo '<option value=' . $template_filename. '>' . $template_name . '</option>';
						}
					}
				?>
			</select>
		</div>
	</div>
	<!-- END: Row Box -->

	<!-- BEGIN: Row Submit -->
	<div class="wpui-row wpui-row-submit">
		<div class="wpui-col-md-12">
			<div class="form-group">
				<input id="generate-bulk-pages" type="submit" class="wpui-secondary-button text-uppercase wpui-min-width-initial" value="Generate Pages">
			</div>
		</div>
	</div>
	<!-- END: Row Submit -->
</form>